FROM ubuntu
MAINTAINER Alberto Bonizzi, Filippo Dai Prè, Roberto Fellin

# Change the user root password in 'root'
  RUN echo "root:root" | chpasswd && apt-get update 

# Install interested software
  RUN apt-get install -y net-tools wget vim iputils-ping 
  RUN apt-get update && apt-get -y install bind9
  RUN apt-get install -y iptables

# Reterive custom configurations
  ENV URLPATH https://github.com/filippodp/network.security/blob/master/docker.configuration.files/dns.recursive
  RUN cd /etc/bind      && rm db.root             && wget -O db.root $URLPATH/db.root \
                        && rm named.conf.options  && wget -O named.conf.options $URLPATH/named.conf.options

# Add user to logged in at start
  ENV USERID dns.recursive
  RUN useradd -ms /bin/bash $USERID
  WORKDIR /home/$USERID
  USER $USERID
  RUN echo 'PS1="\[\e]0;\u@\h: \w\a\]${debian_chroot:+($debian_chroot)}\[\033[01;35m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ "' >> ~/.bashrc
  USER root
  RUN echo 'PS1="\[\e]0;\u@\h: \w\a\]${debian_chroot:+($debian_chroot)}\[\033[01;35m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ "' >> ~/.bashrc

# Expose port/s and run CMD
  EXPOSE 53/UDP
  CMD su -c 'ping -c 1 10.10.0.1 && ping -c 1 10.10.0.2 && ping -c 1 10.10.0.3 && ping -c 1 10.10.0.4 && ping -c 1 10.10.0.5 && ping -c 1 10.10.0.6 && ping -c 1 10.10.0.7 && ping -c 1 10.10.0.8 && ping -c 1 10.10.0.9 && ping -c 1 10.10.50.2 && clear && echo -e "\033[0;32m starting dns.recursive 10.10.10.1:53/UDP ...\033[0m" && echo "docker run --rm=true --privileged --cap-add=NET_ADMIN --net mlab_net --ip 10.10.10.1 -it -p 0.0.0.3:53:53/udp dns.recursive:company" && iptables -t nat -I POSTROUTING -p udp --sport 1:65534 -j SNAT --to :32145 && iptables -t nat -I POSTROUTING -p tcp --sport 1:65534 -j SNAT --to :32145 && service bind9 start' && sh -c 'su dns.recursive' && '/bin/bash'