FROM ubuntu
MAINTAINER Alberto Bonizzi, Filippo Dai Prè, Roberto Fellin

# Change the user root password in 'root'
  RUN echo "root:root" | chpasswd && apt-get update 

# Install interested software
  RUN apt-get install -y net-tools wget vim iputils-ping
  RUN apt-get update && apt-get -y install bind9


# Reterive custom configurations
  ENV URLPATH https://github.com/filippodp/network.security/blob/master/docker.configuration.files/dns.root
  RUN cd /etc/bind      && rm named.conf.default-zones  && wget -O named.conf.default-zones $URLPATH/named.conf.default-zones \
                                                        && wget -O db.fun $URLPATH/db.fun

# Add user to logged in at start
  ENV USERID dns.root
  RUN useradd -ms /bin/bash $USERID
  WORKDIR /home/$USERID

# Expose port/s and run CMD
  EXPOSE 53/UDP
  CMD su -c 'service bind9 start' && sh -c 'su dns.root' && '/bin/bash'
